# Generated by Django 3.2 on 2021-12-07 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answered', models.BooleanField(default=False)),
                ('Price', models.IntegerField(default=0)),
                ('hasPaid', models.BooleanField(default=False)),
                ('UserRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(default=False)),
                ('isPending', models.BooleanField(default=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('SubjectRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST_API.subject')),
                ('UserRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
