# Generated by Django 3.2 on 2021-12-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='File',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='File',
            field=models.CharField(default='', max_length=200),
        ),
    ]
