# Generated by Django 3.2 on 2021-12-17 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0002_auto_20211213_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='File',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='File',
        ),
        migrations.AddField(
            model_name='answer',
            name='FileRef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='REST_API.file'),
        ),
        migrations.AddField(
            model_name='subject',
            name='FileRef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='REST_API.file'),
        ),
    ]
